// Code generated by hand once and maintained the same way. Thirty-two
// registers in three widths plus eight masks is a list nobody should type
// twice, but it is also a list that will never change again — the vector
// files are closed sets, and the next thing to add registers to this
// architecture is APX, which adds general-purpose ones. So this is a
// generated block in the sense that it was produced mechanically, not in the
// sense that a tool regenerates it.

package amd64

import "github.com/vertex-language/amd64/reg"

// The vector registers. Unlike the numbered general-purpose registers these
// keep their spelling exactly: reg.XMM0 is amd64.XMM0, because no type name
// in reg claims the identifier the way R8 claims r8's.
//
// Registers 16 through 31 exist only under AVX-512. Their fifth encoding bit
// has no home in a legacy or VEX prefix, so naming one in a form with no EVEX
// encoding is a refusal from the encoder rather than a silently truncated
// register number. They are declared here regardless, because the register
// file is a fact about the architecture and the table's coverage is not.

type (
	Xmm = reg.Xmm
	Ymm = reg.Ymm
	Zmm = reg.Zmm
	K   = reg.K
)

const (
	XMM0, XMM1, XMM2, XMM3 = reg.XMM0, reg.XMM1, reg.XMM2, reg.XMM3
	XMM4, XMM5, XMM6, XMM7 = reg.XMM4, reg.XMM5, reg.XMM6, reg.XMM7

	XMM8, XMM9, XMM10, XMM11   = reg.XMM8, reg.XMM9, reg.XMM10, reg.XMM11
	XMM12, XMM13, XMM14, XMM15 = reg.XMM12, reg.XMM13, reg.XMM14, reg.XMM15

	XMM16, XMM17, XMM18, XMM19 = reg.XMM16, reg.XMM17, reg.XMM18, reg.XMM19
	XMM20, XMM21, XMM22, XMM23 = reg.XMM20, reg.XMM21, reg.XMM22, reg.XMM23
	XMM24, XMM25, XMM26, XMM27 = reg.XMM24, reg.XMM25, reg.XMM26, reg.XMM27
	XMM28, XMM29, XMM30, XMM31 = reg.XMM28, reg.XMM29, reg.XMM30, reg.XMM31
)

const (
	YMM0, YMM1, YMM2, YMM3 = reg.YMM0, reg.YMM1, reg.YMM2, reg.YMM3
	YMM4, YMM5, YMM6, YMM7 = reg.YMM4, reg.YMM5, reg.YMM6, reg.YMM7

	YMM8, YMM9, YMM10, YMM11   = reg.YMM8, reg.YMM9, reg.YMM10, reg.YMM11
	YMM12, YMM13, YMM14, YMM15 = reg.YMM12, reg.YMM13, reg.YMM14, reg.YMM15

	YMM16, YMM17, YMM18, YMM19 = reg.YMM16, reg.YMM17, reg.YMM18, reg.YMM19
	YMM20, YMM21, YMM22, YMM23 = reg.YMM20, reg.YMM21, reg.YMM22, reg.YMM23
	YMM24, YMM25, YMM26, YMM27 = reg.YMM24, reg.YMM25, reg.YMM26, reg.YMM27
	YMM28, YMM29, YMM30, YMM31 = reg.YMM28, reg.YMM29, reg.YMM30, reg.YMM31
)

const (
	ZMM0, ZMM1, ZMM2, ZMM3 = reg.ZMM0, reg.ZMM1, reg.ZMM2, reg.ZMM3
	ZMM4, ZMM5, ZMM6, ZMM7 = reg.ZMM4, reg.ZMM5, reg.ZMM6, reg.ZMM7

	ZMM8, ZMM9, ZMM10, ZMM11   = reg.ZMM8, reg.ZMM9, reg.ZMM10, reg.ZMM11
	ZMM12, ZMM13, ZMM14, ZMM15 = reg.ZMM12, reg.ZMM13, reg.ZMM14, reg.ZMM15

	ZMM16, ZMM17, ZMM18, ZMM19 = reg.ZMM16, reg.ZMM17, reg.ZMM18, reg.ZMM19
	ZMM20, ZMM21, ZMM22, ZMM23 = reg.ZMM20, reg.ZMM21, reg.ZMM22, reg.ZMM23
	ZMM24, ZMM25, ZMM26, ZMM27 = reg.ZMM24, reg.ZMM25, reg.ZMM26, reg.ZMM27
	ZMM28, ZMM29, ZMM30, ZMM31 = reg.ZMM28, reg.ZMM29, reg.ZMM30, reg.ZMM31
)

// The opmask registers. K0 is an ordinary source and destination for the mask
// instructions themselves and is the one register that cannot fill an EVEX
// write-mask slot, because that encoding in the aaa field means "no masking".
// reg.K.Writable is the predicate, and the operand layer refuses .Mask(K0)
// rather than emitting an unmasked instruction that reads as masked.
const (
	K0, K1, K2, K3 = reg.K0, reg.K1, reg.K2, reg.K3
	K4, K5, K6, K7 = reg.K4, reg.K5, reg.K6, reg.K7
)

// The other register files, re-exported for the tranches that will need them.
// St and Mm arrive with the x87 and MMX tranches; Cr, Dr and Tmm with the
// system and AMX ones. The types are here now so those files add rows and
// methods rather than also having to add a name to the root.
type (
	St  = reg.St
	Mm  = reg.Mm
	Cr  = reg.Cr
	Dr  = reg.Dr
	Tmm = reg.Tmm
)
